# Generated by Django 6.0.2 on 2026-03-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('name_year_hash', models.CharField(max_length=64, unique=True)),
                ('actors', models.ManyToManyField(related_name='films', to='csfdtop.actor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'year'), name='unique_film_name_year')],
            },
        ),
    ]
