# Generated by Django 6.0.2 on 2026-03-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("csfd_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_normalized", models.CharField(editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("csfd_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_normalized", models.CharField(editable=False, max_length=255)),
                ("year", models.PositiveSmallIntegerField()),
                ("actors", models.ManyToManyField(related_name="films", to="csfdtop.actor")),
            ],
        ),
    ]
