# Generated by Django 6.0.2 on 2026-03-01 22:11

from django.db import migrations, models

from csfdtop.utils import normalize_text


def normalize_existing_names(apps, schema_editor):
    Actor = apps.get_model("csfdtop", "Actor")
    Film = apps.get_model("csfdtop", "Film")

    # Update Actors
    for actor in Actor.objects.all():
        actor.name_normalized = normalize_text(actor.name)
        actor.save()

    # Update Films
    for film in Film.objects.all():
        film.name_normalized = normalize_text(film.name)
        film.save()


class Migration(migrations.Migration):
    dependencies = [
        ("csfdtop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="name_normalized",
            field=models.CharField(
                db_index=True, default="", editable=False, max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="film",
            name="name_normalized",
            field=models.CharField(
                db_index=True, default="", editable=False, max_length=255
            ),
            preserve_default=False,
        ),
        migrations.RunPython(normalize_existing_names),
    ]
